# Generated by Django 2.1.1 on 2020-05-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('organiser', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('participant', models.CharField(max_length=10000)),
            ],
        ),
    ]
