# Generated by Django 2.1.1 on 2020-05-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='organiser',
            new_name='mainorg',
        ),
    ]
