# Generated by Django 3.0.6 on 2020-05-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200527_0736'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('transcript', models.CharField(max_length=100000)),
                ('audio_file', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
