# Generated by Django 2.1.1 on 2020-05-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transcript',
            old_name='email',
            new_name='meeting_id',
        ),
        migrations.AddField(
            model_name='meeting',
            name='ended_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
